### ISSUE TITLE
More Level Crap

### ISSUE THREAD

**Issue by bbeck13** [bbeck13/RhythmRunner#106]
the level needs more stuff, we have an enemy model to add in and some behavior that goes along with them

**Comment by josepharhar** [comment]
Powerups
- triple jump
- gliding
- slowmo

**Comment by bbeck13** [comment]
https://github.com/bbeck13/RhythmRunner/pull/124
Don't know about power up's these should be pretty easy to add but I don't know If I'll have time
for 75% that is

**Comment by Matthew-Stewart** [comment]
See #179
