### ISSUE TITLE
Player Bounding Box Too Big

### ISSUE THREAD

**Issue by alexottoboni** [bbeck13/RhythmRunner#129]
The player dies really easily for seemingly no reason, I think it is because the bounding box extends beyond the actual model by a good amount. Getting too close to the side of a block or a rock kills you. 

I know the box is based on the shape size of the object, but we should adjust it just for the player to be slightly smaller than it is.

**Comment by josepharhar** [comment]
i just changed a bunch of stuff related to that. do you think you could make it draw the outline of the bounding box in debug mode? i tried to earlier but i havent written a single line of glsl in this project lol

**Comment by alexottoboni** [comment]
I think it should be easy to draw points where the 8 corners of the box are.

**Comment by josepharhar** [comment]
Does anyone think it would be good to add collision tolerance to the front/sides/rear of collisions in addition to the tolerance we have for vertical collisions?

**Comment by josepharhar** [comment]
If nobody has any issues with my last comment, I am going to implement it

**Comment by bbeck13** [comment]
@josepharhar  that sound reasonable. I'm for that idea
