### ISSUE TITLE
Jump through platforms bug

### ISSUE THREAD

**Issue by Matthew-Stewart** [bbeck13/RhythmRunner#152]
If you land on a rising platform and jump towards the beginning of it, you will "fall through" (the platform will rise up through you).

**Comment by josepharhar** [comment]
Is this just happening on my new branch? It sounds like something I could have broke

**Comment by Matthew-Stewart** [comment]
I believe this has always been an issue, but I'll double check

**Comment by Matthew-Stewart** [comment]
yep this happens on master. It also happens with falling platforms but is much less noticeable

**Comment by josepharhar** [comment]
Thanks for checking. I don't really know anything about this issue though

**Comment by josepharhar** [comment]
I think I fixed it, see if the bug is still there on `origin/jarhar.platforms`

**Comment by josepharhar** [comment]
@bbeck13 fixed in #162
