### ISSUE TITLE
Segfault on glewInit() on linux

### ISSUE THREAD

**Issue by bbeck13** [bbeck13/RhythmRunner#16]
looking at some opengl forums this appears to be due to some hardware settings yada yada I'll dig some more into this

**Comment by josepharhar** [comment]
There is no segfault or crashing on windows. Are there also no issues on OS X?

**Comment by Matthew-Stewart** [comment]
@josepharhar No issues on OS X

**Comment by bbeck13** [comment]
I've been looking into this and it seems to be specific to the way we're using glew (built statically as a submodule) it works for mac and windows because they have all their hardware drivers built into the os but this is not true for linux so we may have to add additional configuration, anyway this is a complicated issue and I might just leave it alone for now if everyone has an environment they can run the game in

**Comment by bbeck13** [comment]
https://github.com/bbeck13/RhythmRunner/pull/97
