### ISSUE TITLE
Postprocessing

### ISSUE THREAD

**Issue by alexottoboni** [bbeck13/RhythmRunner#163]
Motion blur or camera shake on jumping. I'm going to do this as my 2nd individual technology. 

Any effect will require rendering our scene to a frame buffer and then drawing a quad that takes up the whole screen with that frame buffer as a texture.

**Comment by josepharhar** [comment]
Using a frame buffer sounds like it could be related to how @Matthew-Stewart is implementing bloom

**Comment by alexottoboni** [comment]
I'll take a look at that branch then.
