### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by josepharhar** [bbeck13/RhythmRunner#174]
we need to create some html stuph for zoe

**Comment by josepharhar** [comment]
Project Report -- this is in the form of a web page and should contain the following information. Also note that links should be relative (not absolute paths), and that you should submit the html and all necessary image and animation files in the same directory. 
- brief description of your project,
- All team members names
- a mini user's guide,
- sample output i.e. images
- a short animation clip of your game is required
- a list of all references used (e.g. tutorials, research papers, etc.)
- A list of what the team implemented for each required technology
- a project executableProject submission (likely thru polylearn) information will be provided later.

**Comment by bbeck13** [comment]
https://bbeck13.github.io/RhythmRunner/
