### ISSUE TITLE
Address Feedback

### ISSUE THREAD

**Issue by josepharhar** [bbeck13/RhythmRunner#188]
![img_1242](https://cloud.githubusercontent.com/assets/7681467/24211284/cd578cbe-0ee8-11e7-9d13-511dec38b796.JPG)
![img_1241](https://cloud.githubusercontent.com/assets/7681467/24211285/cd6bd912-0ee8-11e7-84de-da281747c7d8.JPG)
![img_1240](https://cloud.githubusercontent.com/assets/7681467/24211286/cd77196c-0ee8-11e7-8ddc-69172900961e.JPG)
![img_1239](https://cloud.githubusercontent.com/assets/7681467/24211287/cd781ee8-0ee8-11e7-8eb3-9a1500eddcc2.JPG)
![img_1238](https://cloud.githubusercontent.com/assets/7681467/24211288/cd79895e-0ee8-11e7-8849-170c09867983.JPG)

**Comment by josepharhar** [comment]
Most of the comments are about the camera angles. Does anyone know how we could set a camera angle that would actually make the game easier? Should the camera be higher above the player looking down or something?

**Comment by bbeck13** [comment]
I added a game mode in the beginning where the user gets to set the camera before they play, they can zoom in/out move the camera around like they would when the game is running

**Comment by josepharhar** [comment]
The only thing left we could do is create an easier level, if we want to

**Comment by bbeck13** [comment]
https://github.com/bbeck13/RhythmRunner/pull/202
