### ISSUE TITLE
SFML CMake Issues on Mac

### ISSUE THREAD

**Issue by alexottoboni** [bbeck13/RhythmRunner#28]
Allowing CMake to setup SFML causes issues on Mac. Installing SFML myself and commenting out the CMake SFML works.

**Comment by bbeck13** [comment]
Is anyone else having this issue it works fine for me without having to install sfml, try uncommenting the lines now that you have it installed, does it still work? If so I'm going to put out a pull request to uncomment those lines for now

I accidentally pushed them in commented out and that broke the build for me

**Comment by alexottoboni** [comment]
I fixed it! Finally! I was missing an OpenAL symlink.

**Comment by bbeck13** [comment]
What did you have to do to fix it? I am having a similar issue when trying to compile on the lab machines @alexottoboni

**Comment by alexottoboni** [comment]
I ran `brew unlink openal-soft` and then `brew link --force openal-soft`, it didn't tell me exactly what it did, but the warning message said that it created symlinks from the brew install directory to the `opt` directory.
