### ISSUE TITLE
fix timing issues

### ISSUE THREAD

**Issue by josepharhar** [bbeck13/RhythmRunner#35]
the game updater should be completely synchronized with the glfw timer and/or the ms elapsed in the song

**Comment by josepharhar** [comment]
the player's "x position" should be kept in sync by the updater

**Comment by Matthew-Stewart** [comment]
Not sure if we need this for 50% or not, but we do need this (the fixed or semi-fixed timestep) to fix the camera. Basically the camera y is based off the CurrentPlatform which is based off of ms elapsed, so currently it gets out of sync with the player x.
