### ISSUE TITLE
Aquila and SFML as git submodule

### ISSUE THREAD

**Issue by alexottoboni** [bbeck13/RhythmRunner#4]
It might be easier for dependencies to have Aquila as a git submodule.

**Comment by josepharhar** [comment]
working on it on the branch jarhar.cmake

**Comment by bbeck13** [comment]
Added some stuff to this end on [sfml_audio](https://github.com/bbeck13/RhythmRunner/tree/sfml_audio)

**Comment by bbeck13** [comment]
Looks like joey got aquila working
