### ISSUE TITLE
window resizing and fullscreen

### ISSUE THREAD

**Issue by josepharhar** [bbeck13/RhythmRunner#41]
should anything in the game be changed based on the size of the window? like how far the camera is away from the player or something like that.

can we do fullscreen? it would be cool

**Comment by Matthew-Stewart** [comment]
Yea i remember fullscreen being pretty straightforward. The only thing i can think of changing would be hud items/size. We want player and platforms to scale with window size (width) so the FoV stays constant, so we dont give an unfair advantage by being able to see further ahead

**Comment by josepharhar** [comment]
@Matthew-Stewart Yeah, thats exactly what I had in mind! If you're up to it I think you should take this issue
