### ISSUE TITLE
Fix and Improve Camera

### ISSUE THREAD

**Issue by Matthew-Stewart** [bbeck13/RhythmRunner#42]
Using jarhar's newest branch as the base code, fix its camera to smoothly flow with the platform positions (current platform's y-value rather than player's y-value). Possibly add option to toggle between following player and following platforms.

**Comment by bbeck13** [comment]
Added support for this new camera modes can easily be added [here](https://github.com/bbeck13/RhythmRunner/blob/master/src/game_updater/GameUpdater.cpp#L333)
