### ISSUE TITLE
Spatial data structure

### ISSUE THREAD

**Issue by josepharhar** [bbeck13/RhythmRunner#48]
"really want to see the hierarchy like an octtree or bounding volume hierarchy
zones with nested values is okay
you could do a quad tree"

**Comment by bbeck13** [comment]
I'm writing some spatial organization into the level each _level segment_ can further be divided into a [oct tree](https://en.wikipedia.org/wiki/Octree)

**Comment by bbeck13** [comment]
Status update I'm going with a full on oct tree, it's implemented but I need to make it more efficient its way too slow atm

**Comment by josepharhar** [comment]
Thanks for taking this one @bbeck13, closing #39 as a duplicate

**Comment by bbeck13** [comment]
https://github.com/bbeck13/RhythmRunner/pull/70
