### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by josepharhar** [bbeck13/RhythmRunner#60]
we are getting blown out of the water by jono's chicken walkers

**Comment by alexottoboni** [comment]
🐔

**Comment by bbeck13** [comment]
Wheel animations animations on death / landing on platform
stuff talked about here https://github.com/bbeck13/RhythmRunner/issues/99

**Comment by josepharhar** [comment]
#128 animates the wheels, but I would still like to make it do something when you jump, when you "duck", and when you die

**Comment by josepharhar** [comment]
The death, wheels, aerial rotations, and ducking are all animated now. I was going to make an actual jumping/landing animation, but it was too difficult and wasn't worth it. There are extra TODOs in the code near animations to add particle and sound effects
