### ISSUE TITLE
Ambient Occlusion

### ISSUE THREAD

**Issue by josepharhar** [bbeck13/RhythmRunner#64]
👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by Matthew-Stewart** [comment]
I guess I accidentally closed this somehow?

**Comment by Matthew-Stewart** [comment]
Ambient Occlusion and/or general lighting improvements

**Comment by bbeck13** [comment]
https://learnopengl.com/#!Advanced-Lighting/SSAO

https://john-chapman-graphics.blogspot.com/2013/01/ssao-tutorial.html

**Comment by alexottoboni** [comment]
This isn't going to happen
