### ISSUE TITLE
Make player move faster based on song rhythm

### ISSUE THREAD

**Issue by josepharhar** [bbeck13/RhythmRunner#72]

**Comment by bbeck13** [comment]
I tried this it's confusing to the player and looks ugly sometimes I might try and add a toned down version

**Comment by josepharhar** [comment]
Yeah I dont really think this works well in our current model. I think a better idea, in order to increase the pace of the game, would be to have more tightly spaced platforms with higher gravity

**Comment by josepharhar** [comment]
Analyzing the rhythm of the game is too hard, and #184 implements variable player speed
