### ISSUE TITLE
Error on quit

### ISSUE THREAD

**Issue by bbeck13** [bbeck13/RhythmRunner#86]
![screen shot 2017-02-16 at 11 25 04 am](https://cloud.githubusercontent.com/assets/8975458/23037269/97d3e16e-f43a-11e6-9aa4-50d791a93184.png)
There is probably a broken destructor somewhere

**Comment by alexottoboni** [comment]
Global objects have an undefined destruction order so if the OpenAl object happens to get destroyed before the SFML sound object you get a segfault:  https://github.com/SFML/SFML/issues/970
