### ISSUE TITLE
Particle System

### ISSUE THREAD

**Issue by alexottoboni** [bbeck13/RhythmRunner#91]
We should have lots of particle effects when things get collected, music changes etc. I think @anguy134 might have claimed this but if he hasn't started I'm pretty juiced about this and want to take it over.

**Comment by bbeck13** [comment]
Take a look at the simple particle systems here https://github.com/bbeck13/Visualizer/blob/master/src/visualizer.cpp the particles grow and move based on the music, it would be easy and cool to add this

**Comment by bbeck13** [comment]
Idea have particles following the player that are lit based on the song (I'll probably have to do this)

**Comment by Matthew-Stewart** [comment]
TRON and/or nyan cat
