### ISSUE TITLE
Clearer winning and losing conditions

### ISSUE THREAD

**Issue by josepharhar** [bbeck13/RhythmRunner#99]
It should be clearer that colliding with the front of a platform will make you lose, and it should be easier to tell what happened when you collide with one. It would also be nice if there was something special at the end of the level to let you know that you got to the end

**Comment by alexottoboni** [comment]
The car should probably stop and explode when it hits something pause for a few seconds then play a record scratch sound then reset the level.

**Comment by josepharhar** [comment]
There is an endgame animation and UI, but we could also add particle and sound effects, and do more with the screen like making it flash red when you lose
